apiVersion: v1
kind: Pod
metadata:
  name: sampleapp-2
  annotations:
      k8s.v1.cni.cncf.io/networks: ipvlan-conf-2
spec:
  containers:
  - name: multitool
    command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: praqma/network-multitool
