apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
      k8s.v1.cni.cncf.io/networks: ipvlan-conf
spec:
  containers:
  - name: nettools
    command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: praqma/network-multitool
