apiVersion: v1
kind: Pod
metadata:
  name: sampleapp-custom-intf-names
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-conf-1@ipvlan1, ipvlan-conf-2@ipvlan2
spec:
  containers:
  - name: centos-network
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
